//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTRPG.Core.SaveManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTRPG.Core.SaveManager.SettingNames", typeof(SettingNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base_Auth_Lockout_Count.
        /// </summary>
        internal static string Auth_LockoutCount {
            get {
                return ResourceManager.GetString("Auth_LockoutCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base_Auth_Lockout_Time.
        /// </summary>
        internal static string Auth_LockoutTime {
            get {
                return ResourceManager.GetString("Auth_LockoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base_Basic_Campaign_GMName.
        /// </summary>
        internal static string Campaign_GMName {
            get {
                return ResourceManager.GetString("Campaign_GMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base_Basic_Campaign_Name.
        /// </summary>
        internal static string Campaign_Name {
            get {
                return ResourceManager.GetString("Campaign_Name", resourceCulture);
            }
        }
    }
}
