//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTRPG.Core.Permissions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Permissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Permissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTRPG.Core.Permissions.Permissions", typeof(Permissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `tblGroupMembers` ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `GID` INTEGER NOT NULL, `UID` INTEGER NOT NULL, FOREIGN KEY(`UID`) REFERENCES `tblUsers`(`UID`), FOREIGN KEY(`GID`) REFERENCES `tblGroups`(`GID`) ).
        /// </summary>
        internal static string Save_Create_tblGroupMembers {
            get {
                return ResourceManager.GetString("Save_Create_tblGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;tblGroupPermissions&quot; ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `GID` INTEGER NOT NULL, `Node` TEXT NOT NULL, `Allow` INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(`GID`) REFERENCES `tblGroups`(`GID`) ).
        /// </summary>
        internal static string Save_Create_tblGroupPermissions {
            get {
                return ResourceManager.GetString("Save_Create_tblGroupPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `tblGroups` ( `GID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `Name` TEXT NOT NULL UNIQUE, `Description` TEXT ).
        /// </summary>
        internal static string Save_Create_tblGroups {
            get {
                return ResourceManager.GetString("Save_Create_tblGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;tblUserPermissions&quot; ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `UID` INTEGER NOT NULL, `Node` TEXT NOT NULL, `Allow` INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(`UID`) REFERENCES `tblUsers`(`UID`) ).
        /// </summary>
        internal static string Save_Create_tblUserPermissions {
            get {
                return ResourceManager.GetString("Save_Create_tblUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER trgPermissions_GroupDeleted BEFORE DELETE ON tblGroups 
        ///BEGIN
        ///	DELETE FROM tblGroupMembers WHERE GID = OLD.GID;
        ///	DELETE FROM tblGroupPermissions WHERE GID = OLD.GID;
        ///END.
        /// </summary>
        internal static string Save_Create_trgPermissions_GroupDeleted {
            get {
                return ResourceManager.GetString("Save_Create_trgPermissions_GroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER trgPermissions_UserDeleted BEFORE DELETE 
        ///ON tblUsers
        ///BEGIN
        /// DELETE FROM tblGroupMembers WHERE UID = OLD.UID;
        /// DELETE FROM tblUserPermissions WHERE UID = OLD.UID;
        ///END;.
        /// </summary>
        internal static string Save_Create_trgPermissions_UserDeleted {
            get {
                return ResourceManager.GetString("Save_Create_trgPermissions_UserDeleted", resourceCulture);
            }
        }
    }
}
