//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTRPG.Core.Authentication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Authentication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authentication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTRPG.Core.Authentication.Authentication", typeof(Authentication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;tblAuth&quot; ( `UID` INTEGER NOT NULL UNIQUE, `Username` TEXT NOT NULL UNIQUE, `Salt` TEXT NOT NULL, `Hash` TEXT NOT NULL, `Security_Attempts` INTEGER NOT NULL DEFAULT 0, `Security_LastAttempt` TEXT NOT NULL, `Security_Disabled` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(`UID`), FOREIGN KEY(`UID`) REFERENCES `tblUsers`(`UID`) ).
        /// </summary>
        internal static string Save_Create_tblAuth {
            get {
                return ResourceManager.GetString("Save_Create_tblAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;tblUsers&quot; ( `UID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `Name` TEXT NOT NULL, `Character_Name` TEXT NOT NULL, `UserColor` TEXT NOT NULL DEFAULT &apos;#FFFF0000&apos;, `isGM` INTEGER NOT NULL DEFAULT 0 ).
        /// </summary>
        internal static string Save_Create_tblUsers {
            get {
                return ResourceManager.GetString("Save_Create_tblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Setting_Default_AttemptCount {
            get {
                return ResourceManager.GetString("Setting_Default_AttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Setting_Default_LockoutTime {
            get {
                return ResourceManager.GetString("Setting_Default_LockoutTime", resourceCulture);
            }
        }
    }
}
